node {
    def app

    stage('Clone repo') {
       checkout scm
    }

    stage('clean install') {
       sh 'mvn -f ./spring-rest-example/pom.xml clean install'
    }
        
    stage('build docker image') {
       app = docker.build("sunlnx/spring-docker-pipeline-test","-f ./spring-rest-example/Dockerfile")
    }

    stage('push docker image') {
       docker.withRegistry('https://registry.hub.docker.com', 'docker-hub') 
       app.push("${env.BUILD_NUMBER}")
       app.push("latest")
    } 
}
