node {
    stage('Clone repository') {
        checkout scm
    }

pipeline {
    agent any
    stages {
        stage('build spring-rest-example') {
            steps {
                sh 'mvn -B clean verify'
            }
        }
    }
}
