server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pattabhia/springcloud-configuration
          search-paths: 'station*'
  security:
    user:
      name: pattabhi
      password: welcome